language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2.101

install:
- dotnet restore

script:
- dotnet build
- dotnet test leetcodesln_test/leetcodesln_test.csproj

notifications:
  email:
    recipients:
      - stan_gai@Hotmail.com
    on_failure: always #default:always