language: csharp
mono: none
dotnet: 2.1.105

install:
- dotnet restore
- dotnet tool install -g coveralls.net --version 1.0.0

script:
- dotnet build
- dotnet test leetcodesln_test/leetcodesln_test.csproj