language: csharp
mono: none
os: linux
dist: xenial
dotnet: 2.2.3

install:
- dotnet restore

script:
- dotnet build
- dotnet test leetcodesln_test/leetcodesln_test.csproj

notifications:
  email:
    recipients:
      - stan_gai@Hotmail.com
    on_success: never #default: change
    on_failure: always #default:always


  # or you can add [ci skip] into your commit's message eg: git commit -m "readme update [ci skip]"